# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Jamal's Website
tagline:          'ayy lmao'
description:      ''
url:              http://jamalblog.github.io
baseurl:          /

author:
  name:           'Jamal Smith'
  url:            https://twitter.com/IAmJamalSmith

paginate:         5

# Custom vars

github:           
  repo:           https://github.com/jamalsmith
